### PR TITLE
Add Discount

### PR DESCRIPTION
**Pull request by AmirChabok**
added discount in project.

### CODE REVIEW

**Comment by MehdiSaeedifar** [comment]
Thank you.
I will merge it ASAP.

**Comment by AmirChabok** [comment]
Thank you.

**Comment by MehdiSaeedifar** [comment]
I have this problem that i show in screen shot, do you know anything about it?
It seems that any price label have this problem.

bug

**Comment by AmirChabok** [comment]
Hello.
Please use the latest version of the changes.[(after update index & widget views)](https://github.com/AmirChabok/IrisStore)
There was  two-price display in the pre-update version but unspecified text , no!

**Comment by MehdiSaeedifar** [comment]
OK, i check it out.

**Comment by MehdiSaeedifar** [comment]
I test it again; the same problem.
I am using this code. Is it correct?
https://github.com/MehdiSaeedifar/IrisStore/tree/6fa2be71a034aacfea76b249317ff76db7d73cfc

**Comment by AmirChabok** [comment]
Yes code is correct and i test on 3 computer and there was no error in any one!

**Comment by MehdiSaeedifar** [comment]
I also test it on 2 different computers and get same result!
Can you please send your pull request to dev branch to find problem by me?

**Comment by AmirChabok** [comment]
I find problem.
The two files (Index & _Widget) were updated on the Github itself.
The issue was resolved after editing in Visual Studio.

**Comment by AmirChabok** [comment]
capture_2018_01_27_08_03_16_584

**Comment by AmirChabok** [comment]
capture_2018_01_27_08_04_06_62
capture_2018_01_27_08_04_42_310
capture_2018_01_27_08_04_59_265

**Comment by MehdiSaeedifar** [comment]
Thanks.

**Comment by AmirChabok** [comment]
Thank you too.

**Pull request merged**
